[package]
name = "clohb"
version = "1.0.0"
authors = ["Jordan Stojanovski"]

[addresses]
clohb = "_"

[dev-addresses]
clohb = "0x12345678"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "main"
subdir = "aptos-framework"

[dev-dependencies]
